name: flutter_template_vip
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  url_launcher: ^6.0.0
  device_info: ^2.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  connectivity: ^3.0.3
  intl: ^0.17.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  google_fonts: ^2.0.0
  fluttertoast: ^8.0.6
  webview_flutter: ^2.0.4



  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/